catalogMode: prefer
cleanupUnusedCatalogs: true
minimumReleaseAge: 1440
shellEmulator: true
packages:
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^6.4.2
  '@babel/core': ^7.28.5
  '@babel/preset-env': ^7.28.5
  '@babel/runtime': ^7.28.4
  '@eslint-react/eslint-plugin': ^2.3.12
  '@react-native-community/cli': ^20.0.2
  '@react-native-community/cli-platform-android': ^20.0.2
  '@react-native-community/cli-platform-ios': ^20.0.2
  '@react-native/babel-preset': ^0.82.1
  '@react-native/codegen': ^0.82.1
  '@react-native/metro-config': ^0.82.1
  '@release-it/conventional-changelog': ^10.0.2
  '@shikijs/core': ^3.19.0
  '@shikijs/engine-oniguruma': ^3.19.0
  '@shikijs/langs': ^3.19.0
  '@shikijs/themes': ^3.19.0
  '@shikijs/types': ^3.19.0
  '@shikijs/vscode-textmate': ^10.0.2
  '@types/react': ~19.2.7
  babel-plugin-module-resolver: ^5.0.2
  del-cli: ^7.0.0
  eslint: ^9.39.1
  eslint-plugin-oxlint: ^1.31.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  expo: ^54.0.27
  oxlint: ^1.31.0
  react: 19.2.1
  react-dom: 19.2.1
  react-native: 0.82.1
  react-native-builder-bob: ^0.40.16
  react-native-safe-area-context: ^5.6.2
  react-native-web: ^0.21.2
  release-it: ^19.0.6
  turbo: ^2.6.3
  typescript: ^5.9.3
