catalogMode: prefer
minimumReleaseAgeExclude:
  - '@rari/lint@0.1.2'
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - ua-parser-js@1.0.41
packages:
  - packages/*
  - examples/*
catalogs:
  babel:
    '@babel/core': 7.29.7
    '@babel/runtime': 7.29.7
    '@types/babel__core': 7.20.5
    babel-plugin-module-resolver: ^5.0.3
  build:
    '@release-it/conventional-changelog': ^12.0.0
    react-native-builder-bob: ^0.43.0
    release-it: ^21.0.2
    vite-plus: ^0.3.0
  eslint:
    '@rari/lint': ^0.1.2
    eslint: ^10.9.1
  react:
    '@react-native/babel-preset': 0.87.0
    '@react-native/codegen': 0.87.0
    '@react-native/gradle-plugin': 0.87.0
    '@react-native/metro-config': 0.87.0
    expo: ^57.0.16
    react: 19.2.8
    react-dom: 19.2.8
    react-native: 0.87.0
    react-native-safe-area-context: ^5.9.1
    react-native-web: ^0.21.2
  react-native-cli:
    '@react-native-community/cli': ^20.2.0
    '@react-native-community/cli-platform-android': ^20.2.0
    '@react-native-community/cli-platform-ios': ^20.2.0
  shiki:
    '@shikijs/core': ^4.4.3
    '@shikijs/engine-oniguruma': ^4.4.3
    '@shikijs/langs': ^4.4.3
    '@shikijs/themes': ^4.4.3
    '@shikijs/types': ^4.4.3
    '@shikijs/vscode-textmate': ^10.0.2
  types:
    '@types/node': ^26.4.0
    '@types/react': 19.2.18
    # https://devblogs.microsoft.com/typescript/announcing-typescript-7-0/#running-side-by-side-with-typescript-6.0
    typescript: npm:@typescript/typescript6@^6.0.2
    typescript-7: npm:typescript@^7.0.2
allowBuilds:
  msgpackr-extract: true
